# Generated by Django 5.1.1 on 2024-09-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='card',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='card',
            name='user',
        ),
        migrations.AlterField(
            model_name='card',
            name='location_image',
            field=models.ImageField(upload_to='location_images/'),
        ),
        migrations.AlterField(
            model_name='card',
            name='professor_image',
            field=models.ImageField(upload_to='professor_images/'),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
